on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Find Lowest Number Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      
    - name: Run Tests
      run: |
        python find_lowest_number.py test_data/test1_input.txt test_data/output1.txt
        python find_lowest_number.py test_data/test2_input.txt test_data/output2.txt
        python find_lowest_number.py test_data/test3_input.txt test_data/output3.txt
          
    - name: Compare Output with Expected
      run: |
        diff test_data/output1.txt test_data/test1_expected.txt
        diff test_data/output2.txt test_data/test2_expected.txt
        diff test_data/output3.txt test_data/test3_expected.txt
